# Generated by Django 4.1.7 on 2025-05-07 09:13

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unicore_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('email', models.EmailField(help_text='Enter an email address that you want to connect to this account.', max_length=255, verbose_name='Email')),
                ('verified_email', models.BooleanField(default=False)),
                ('phone_number', models.CharField(help_text='Enter a phone number that you want to connect to this account.', max_length=20, verbose_name='Phone number')),
                ('is_superuser', models.BooleanField(help_text='Designates whether the user is a superuser')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('ssn', models.CharField(max_length=13, unique=True, verbose_name='Social security number')),
                ('registration_year', models.CharField(blank=True, help_text='Enter the year you started studying at the TekNat faculty', max_length=4, validators=[django.core.validators.RegexValidator(message='Please enter a valid year', regex='^20\\d{2}$')], verbose_name='Registration year')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('nonmember', 'Nonmember'), ('member', 'Member'), ('alumnus', 'Alumnus')], default='unknown', max_length=20, verbose_name='Membership status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('appointed', 'Appointed'), ('turned_down', 'Turned down')], max_length=20, verbose_name='Status')),
                ('cover_letter', models.TextField(help_text='Present yourself and state why you are\n         who we are looking for', verbose_name='Cover Letter')),
                ('qualifications', models.TextField(help_text='Give a summary of relevant qualifications', verbose_name='Qualifications')),
                ('gdpr', models.BooleanField(default=False, help_text='\n            I accept that my data is saved in accordance\n            with Uppsala Union of Engineering and Science Students integrity\n            policy that can be found within the link:\n        ', verbose_name='GDPR')),
                ('rejection_date', models.DateField(blank=True, null=True, verbose_name='Rejection date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MandateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ManyToManyField(related_name='MandateHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(help_text='Enter the abbreviation of the section', max_length=20, verbose_name='Abbreviation')),
                ('section_en', models.CharField(help_text='Enter the name of the section in English', max_length=255, verbose_name='Section name in English')),
                ('section_sv', models.CharField(help_text='Enter the name of the section in Swedish', max_length=255, verbose_name='Section name in Swedish')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Enter the name of the team', max_length=255, verbose_name='English team name')),
                ('name_sv', models.CharField(help_text='Enter the name of the team', max_length=255, verbose_name='Swedish team name')),
                ('logo', models.ImageField(blank=True, help_text='Upload a logo for the team', upload_to='../media/', verbose_name='Logo')),
                ('desc_en', models.TextField(blank=True, help_text='Enter a description of the team', verbose_name='English team description')),
                ('desc_sv', models.TextField(blank=True, help_text='Enter a description of the team', verbose_name='Swedish team description')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Enter the name of the section in English', max_length=255, verbose_name='English section name')),
                ('name_sv', models.CharField(help_text='Enter the name of the section in Swedish', max_length=255, verbose_name='Swedish section name')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_programs', to='backend.section')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('admin', 'Admin'), ('fum', 'FUM'), ('board', 'Board'), ('presidium', 'Presidium'), ('group_leader', 'Group Leader'), ('involved', 'Involved')], max_length=255, verbose_name='Role type')),
                ('archived', models.BooleanField(default=False, help_text='Hide the role from menus', verbose_name='Archived')),
                ('title_en', models.CharField(help_text='Enter the name of the role', max_length=255, verbose_name='English role name')),
                ('title_sv', models.CharField(help_text='Enter the name of the role', max_length=255, verbose_name='Swedish role name')),
                ('description_en', models.TextField(help_text='Enter a description of the role', verbose_name='English role description')),
                ('description_sv', models.TextField(help_text='Enter a description of the role', verbose_name='Swedish role description')),
                ('contact_email', models.EmailField(help_text='The email address for the current position holder', max_length=254, verbose_name='Contact email address')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='backend.team')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_num', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('title', models.CharField(blank=True, help_text='Enter the title or role of the reference', max_length=255, verbose_name='Title/Role')),
                ('email', models.EmailField(blank=True, help_text='Enter the email of the reference', max_length=254, verbose_name='Email')),
                ('comment', models.CharField(blank=True, help_text='Enter a comment about the reference', max_length=511, verbose_name='Comment')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='backend.application')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_start', models.DateField(default=datetime.date.today, verbose_name='Start of recruitment')),
                ('recruitment_end', models.DateField(verbose_name='Recruitment deadline')),
                ('appointed', models.IntegerField(default=1, help_text='Enter the number of people to appoint', verbose_name='Number of people appointed')),
                ('term_from', models.DateTimeField(verbose_name='Date of appointment')),
                ('term_end', models.DateField(verbose_name='End date of the appointment')),
                ('comment_eng', models.TextField(blank=True, verbose_name='Comment in English')),
                ('comment_sv', models.TextField(blank=True, verbose_name='Comment in Swedish')),
                ('mandate_history', models.ManyToManyField(related_name='positions', to='backend.mandatehistory')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='backend.role')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='backend.position'),
        ),
        migrations.AddField(
            model_name='member',
            name='study_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.studyprogram', verbose_name='Study program'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
