# Generated by Django 4.1.7 on 2025-11-26 15:52

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "appointed_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Appointed date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("appointed", "Appointed"),
                            ("resigned", "Resigned"),
                            ("terminated", "Terminated"),
                        ],
                        default="appointed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resignation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resignation date"
                    ),
                ),
                (
                    "resignation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resignation reason"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "appointed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Appointed by",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.RemoveField(
            model_name="position",
            name="mandate_history",
        ),
        migrations.DeleteModel(
            name="MandateHistory",
        ),
        migrations.AddField(
            model_name="appointment",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="backend.position",
                verbose_name="Position",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="positions",
            field=models.ManyToManyField(
                related_name="members",
                through="backend.Appointment",
                to="backend.position",
                verbose_name="Positions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("member", "position")},
        ),
    ]
