# Generated by Django 4.1.7 on 2025-12-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_appointment_remove_position_mandate_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
