# Generated by Django 4.1.7 on 2025-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_appointment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="rejection_date",
        ),
        migrations.AddField(
            model_name="application",
            name="decision_date",
            field=models.DateField(blank=True, null=True, verbose_name="Decision date"),
        ),
        migrations.AlterField(
            model_name="position",
            name="term_from",
            field=models.DateField(verbose_name="Date of appointment"),
        ),
    ]
