# Generated by Django 4.1.7 on 2026-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_application_rejection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a logo for the team', upload_to='team_logos/', verbose_name='Logo'),
        ),
    ]
