# Generated by Django 4.1.7 on 2026-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_0006_alter_appointment_member_0006_role_role_description_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a superuser'),
        ),
    ]
