# Generated by Django 6.0.5 on 2026-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_add_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='positions',
            field=models.ManyToManyField(related_name='members', through='backend.Appointment', through_fields=('member', 'position'), to='backend.position', verbose_name='Positions'),
        ),
    ]
