# Generated by Django 4.1.7 on 2026-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_add_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='degree',
            field=models.CharField(blank=True, choices=[('bsc', 'Bachelor of Science'), ('msc', 'Master of Science'), ('msceng', 'Master of Science in Engineering'), ('be', 'Bachelor of Engineering')], default='', help_text='The degree awarded by this study program', max_length=20, verbose_name='Degree'),
        ),
    ]
