# Generated by Django 4.1.7 on 2026-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_studyprogram_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='election_email',
            field=models.EmailField(blank=True, default='', help_text='The email address used for nominations/elections to this role', max_length=254, verbose_name='Election email address'),
        ),
    ]
