# Generated by Django 4.1.7 on 2026-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_role_election_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='team',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='section',
        ),
        migrations.AddField(
            model_name='role',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='The teams this role belongs to', related_name='roles', to='backend.team', verbose_name='Teams'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='The sections this study program belongs to', related_name='study_programs', to='backend.section', verbose_name='Sections'),
        ),
    ]
