# Generated by Django 4.1.7 on 2026-07-08 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_role_team_remove_studyprogram_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.section', verbose_name='Section'),
        ),
    ]
